// Mocks generated by Mockito 5.4.6 from annotations
// in freegosy/test/widgets/library_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:io' as _i10;
import 'dart:typed_data' as _i11;

import 'package:flutter/foundation.dart' as _i2;
import 'package:freegosy/core/emulator/linux_strategies/linux_environment_strategy.dart'
    as _i5;
import 'package:freegosy/core/romm/library_snapshot_service.dart' as _i14;
import 'package:freegosy/core/romm/romm_models.dart' as _i3;
import 'package:freegosy/core/romm/romm_service.dart' as _i6;
import 'package:freegosy/core/storage/app_preferences.dart' as _i9;
import 'package:freegosy/core/storage/directory_service.dart' as _i12;
import 'package:freegosy/core/storage/file_system_index.dart' as _i4;
import 'package:freegosy/core/storage/metadata_cache_service.dart' as _i15;
import 'package:freegosy/core/storage/rom_mapping_service.dart' as _i13;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeValueNotifier_0<T> extends _i1.SmartFake
    implements _i2.ValueNotifier<T> {
  _FakeValueNotifier_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRomMConfig_1 extends _i1.SmartFake implements _i3.RomMConfig {
  _FakeRomMConfig_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRommCapabilities_2 extends _i1.SmartFake
    implements _i3.RommCapabilities {
  _FakeRommCapabilities_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStorageStatus_3 extends _i1.SmartFake implements _i4.StorageStatus {
  _FakeStorageStatus_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLinuxEnvironmentStrategy_4 extends _i1.SmartFake
    implements _i5.LinuxEnvironmentStrategy {
  _FakeLinuxEnvironmentStrategy_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RommService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRommService extends _i1.Mock implements _i6.RommService {
  MockRommService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ValueNotifier<bool> get isOffline =>
      (super.noSuchMethod(
            Invocation.getter(#isOffline),
            returnValue: _FakeValueNotifier_0<bool>(
              this,
              Invocation.getter(#isOffline),
            ),
          )
          as _i2.ValueNotifier<bool>);

  @override
  _i3.RomMConfig get config =>
      (super.noSuchMethod(
            Invocation.getter(#config),
            returnValue: _FakeRomMConfig_1(this, Invocation.getter(#config)),
          )
          as _i3.RomMConfig);

  @override
  String get saveSlot =>
      (super.noSuchMethod(
            Invocation.getter(#saveSlot),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#saveSlot),
            ),
          )
          as String);

  @override
  _i3.RommCapabilities get capabilities =>
      (super.noSuchMethod(
            Invocation.getter(#capabilities),
            returnValue: _FakeRommCapabilities_2(
              this,
              Invocation.getter(#capabilities),
            ),
          )
          as _i3.RommCapabilities);

  @override
  String get authHeader =>
      (super.noSuchMethod(
            Invocation.getter(#authHeader),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#authHeader),
            ),
          )
          as String);

  @override
  void updateConfig(_i3.RomMConfig? newConfig) => super.noSuchMethod(
    Invocation.method(#updateConfig, [newConfig]),
    returnValueForMissingStub: null,
  );

  @override
  void startHeartbeat() => super.noSuchMethod(
    Invocation.method(#startHeartbeat, []),
    returnValueForMissingStub: null,
  );

  @override
  void stopHeartbeat() => super.noSuchMethod(
    Invocation.method(#stopHeartbeat, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> refreshToken(_i9.AppPreferences? prefs) =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, [prefs]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i3.RommCapabilities> fetchCapabilities() =>
      (super.noSuchMethod(
            Invocation.method(#fetchCapabilities, []),
            returnValue: _i8.Future<_i3.RommCapabilities>.value(
              _FakeRommCapabilities_2(
                this,
                Invocation.method(#fetchCapabilities, []),
              ),
            ),
          )
          as _i8.Future<_i3.RommCapabilities>);

  @override
  _i8.Future<String?> registerDevice({
    required String? name,
    required String? platform,
    String? clientVersion,
    bool? allowExisting = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registerDevice, [], {
              #name: name,
              #platform: platform,
              #clientVersion: clientVersion,
              #allowExisting: allowExisting,
            }),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<_i3.Game?> getGame(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getGame, [id]),
            returnValue: _i8.Future<_i3.Game?>.value(),
          )
          as _i8.Future<_i3.Game?>);

  @override
  _i8.Future<List<_i3.Platform>> getPlatforms() =>
      (super.noSuchMethod(
            Invocation.method(#getPlatforms, []),
            returnValue: _i8.Future<List<_i3.Platform>>.value(<_i3.Platform>[]),
          )
          as _i8.Future<List<_i3.Platform>>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getCollections() =>
      (super.noSuchMethod(
            Invocation.method(#getCollections, []),
            returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i8.Future<List<Map<String, dynamic>>>);

  @override
  String? resolveCoverUrl(_i3.Game? game) =>
      (super.noSuchMethod(Invocation.method(#resolveCoverUrl, [game]))
          as String?);

  @override
  _i8.Future<List<_i3.Game>> getGames(String? platformId) =>
      (super.noSuchMethod(
            Invocation.method(#getGames, [platformId]),
            returnValue: _i8.Future<List<_i3.Game>>.value(<_i3.Game>[]),
          )
          as _i8.Future<List<_i3.Game>>);

  @override
  _i8.Future<List<_i3.Game>> getAllGames({String? platformId}) =>
      (super.noSuchMethod(
            Invocation.method(#getAllGames, [], {#platformId: platformId}),
            returnValue: _i8.Future<List<_i3.Game>>.value(<_i3.Game>[]),
          )
          as _i8.Future<List<_i3.Game>>);

  @override
  _i8.Future<List<_i3.Game>> getRecentlyAdded({int? limit = 15}) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentlyAdded, [], {#limit: limit}),
            returnValue: _i8.Future<List<_i3.Game>>.value(<_i3.Game>[]),
          )
          as _i8.Future<List<_i3.Game>>);

  @override
  _i8.Future<List<_i3.Game>> getRecentlyPlayed({int? limit = 15}) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentlyPlayed, [], {#limit: limit}),
            returnValue: _i8.Future<List<_i3.Game>>.value(<_i3.Game>[]),
          )
          as _i8.Future<List<_i3.Game>>);

  @override
  _i8.Future<List<_i3.Game>> searchRoms({
    String? sha1,
    String? md5,
    String? search,
    String? platformId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchRoms, [], {
              #sha1: sha1,
              #md5: md5,
              #search: search,
              #platformId: platformId,
            }),
            returnValue: _i8.Future<List<_i3.Game>>.value(<_i3.Game>[]),
          )
          as _i8.Future<List<_i3.Game>>);

  @override
  _i8.Future<({List<_i3.Game> games, int total})> getGamesPage({
    int? offset = 0,
    int? limit = 50,
    String? platformId,
    String? search,
    List<String>? genres = const [],
    List<String>? regions = const [],
    List<String>? languages = const [],
    List<String>? collections = const [],
    List<String>? statuses = const [],
    bool? lastPlayed,
    bool? withCharIndex = false,
    bool? withFilterValues = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getGamesPage, [], {
              #offset: offset,
              #limit: limit,
              #platformId: platformId,
              #search: search,
              #genres: genres,
              #regions: regions,
              #languages: languages,
              #collections: collections,
              #statuses: statuses,
              #lastPlayed: lastPlayed,
              #withCharIndex: withCharIndex,
              #withFilterValues: withFilterValues,
            }),
            returnValue: _i8.Future<({List<_i3.Game> games, int total})>.value((
              games: <_i3.Game>[],
              total: 0,
            )),
          )
          as _i8.Future<({List<_i3.Game> games, int total})>);

  @override
  _i8.Future<_i3.Game?> getRandomGame() =>
      (super.noSuchMethod(
            Invocation.method(#getRandomGame, []),
            returnValue: _i8.Future<_i3.Game?>.value(),
          )
          as _i8.Future<_i3.Game?>);

  @override
  _i8.Future<List<_i3.SaveFile>> getSaves(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#getSaves, [gameId]),
            returnValue: _i8.Future<List<_i3.SaveFile>>.value(<_i3.SaveFile>[]),
          )
          as _i8.Future<List<_i3.SaveFile>>);

  @override
  String getDownloadUrl(_i3.Game? game) =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadUrl, [game]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#getDownloadUrl, [game]),
            ),
          )
          as String);

  @override
  _i8.Future<({Map<String, dynamic>? conflict, bool ok})> uploadSave(
    String? gameId,
    _i10.File? saveFile, {
    String? emulator,
    String? slot,
    String? deviceId,
    bool? autocleanup = false,
    int? autocleanupLimit = 5,
    bool? overwrite = false,
    _i10.File? screenshotFile,
    String? overrideFilename,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadSave,
              [gameId, saveFile],
              {
                #emulator: emulator,
                #slot: slot,
                #deviceId: deviceId,
                #autocleanup: autocleanup,
                #autocleanupLimit: autocleanupLimit,
                #overwrite: overwrite,
                #screenshotFile: screenshotFile,
                #overrideFilename: overrideFilename,
              },
            ),
            returnValue:
                _i8.Future<({Map<String, dynamic>? conflict, bool ok})>.value((
                  conflict: null,
                  ok: false,
                )),
          )
          as _i8.Future<({Map<String, dynamic>? conflict, bool ok})>);

  @override
  _i8.Future<bool> deleteSaves(List<int>? saveIds) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSaves, [saveIds]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<void> pruneOldSaves(String? gameId, {int? keepCount = 5}) =>
      (super.noSuchMethod(
            Invocation.method(
              #pruneOldSaves,
              [gameId],
              {#keepCount: keepCount},
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getSavesList(
    String? gameId, {
    String? deviceId,
    String? slot,
    bool? requireSuccess = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getSavesList,
              [gameId],
              {
                #deviceId: deviceId,
                #slot: slot,
                #requireSuccess: requireSuccess,
              },
            ),
            returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<Map<String, dynamic>?> getLatestSave(
    String? gameId, {
    String? deviceId,
    String? slot,
    bool? requireSuccess = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getLatestSave,
              [gameId],
              {
                #deviceId: deviceId,
                #slot: slot,
                #requireSuccess: requireSuccess,
              },
            ),
            returnValue: _i8.Future<Map<String, dynamic>?>.value(),
          )
          as _i8.Future<Map<String, dynamic>?>);

  @override
  _i8.Future<_i11.Uint8List?> downloadSave(
    String? saveUrl, {
    _i9.AppPreferences? prefs,
    String? deviceId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadSave,
              [saveUrl],
              {#prefs: prefs, #deviceId: deviceId},
            ),
            returnValue: _i8.Future<_i11.Uint8List?>.value(),
          )
          as _i8.Future<_i11.Uint8List?>);

  @override
  _i8.Future<void> recordPlaySession({
    required String? romId,
    required String? deviceId,
    required DateTime? startTime,
    required DateTime? endTime,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#recordPlaySession, [], {
              #romId: romId,
              #deviceId: deviceId,
              #startTime: startTime,
              #endTime: endTime,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<_i3.Firmware>> getFirmware({String? platformId}) =>
      (super.noSuchMethod(
            Invocation.method(#getFirmware, [], {#platformId: platformId}),
            returnValue: _i8.Future<List<_i3.Firmware>>.value(<_i3.Firmware>[]),
          )
          as _i8.Future<List<_i3.Firmware>>);

  @override
  String getFirmwareDownloadUrl(_i3.Firmware? firmware) =>
      (super.noSuchMethod(
            Invocation.method(#getFirmwareDownloadUrl, [firmware]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#getFirmwareDownloadUrl, [firmware]),
            ),
          )
          as String);

  @override
  _i8.Future<_i11.Uint8List?> downloadFirmware(
    _i3.Firmware? firmware, {
    void Function(int, int)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadFirmware,
              [firmware],
              {#onProgress: onProgress},
            ),
            returnValue: _i8.Future<_i11.Uint8List?>.value(),
          )
          as _i8.Future<_i11.Uint8List?>);

  @override
  _i8.Future<bool> updateRomProps(
    String? romId,
    _i9.AppPreferences? prefs, {
    bool? backlogged,
    bool? nowPlaying,
    int? rating,
    String? status,
    int? completion,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateRomProps,
              [romId, prefs],
              {
                #backlogged: backlogged,
                #nowPlaying: nowPlaying,
                #rating: rating,
                #status: status,
                #completion: completion,
              },
            ),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<List<_i3.RomNote>> getRomNotes(String? romId) =>
      (super.noSuchMethod(
            Invocation.method(#getRomNotes, [romId]),
            returnValue: _i8.Future<List<_i3.RomNote>>.value(<_i3.RomNote>[]),
          )
          as _i8.Future<List<_i3.RomNote>>);

  @override
  _i8.Future<bool> createRomNote(
    String? romId,
    String? title,
    String? content,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createRomNote, [romId, title, content]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> deleteRomNote(String? romId, int? noteId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRomNote, [romId, noteId]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);
}

/// A class which mocks [DirectoryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDirectoryService extends _i1.Mock implements _i12.DirectoryService {
  MockDirectoryService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get romsRootPath =>
      (super.noSuchMethod(
            Invocation.getter(#romsRootPath),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#romsRootPath),
            ),
          )
          as String);

  @override
  String get emulatorsRootPath =>
      (super.noSuchMethod(
            Invocation.getter(#emulatorsRootPath),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#emulatorsRootPath),
            ),
          )
          as String);

  @override
  String get linuxSyncPreset =>
      (super.noSuchMethod(
            Invocation.getter(#linuxSyncPreset),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#linuxSyncPreset),
            ),
          )
          as String);

  @override
  bool get useFlatEmulatorLayout =>
      (super.noSuchMethod(
            Invocation.getter(#useFlatEmulatorLayout),
            returnValue: false,
          )
          as bool);

  @override
  _i4.StorageStatus get status =>
      (super.noSuchMethod(
            Invocation.getter(#status),
            returnValue: _FakeStorageStatus_3(this, Invocation.getter(#status)),
          )
          as _i4.StorageStatus);

  @override
  bool get isSteamDeck =>
      (super.noSuchMethod(Invocation.getter(#isSteamDeck), returnValue: false)
          as bool);

  @override
  _i5.LinuxEnvironmentStrategy get activeLinuxEnvironment =>
      (super.noSuchMethod(
            Invocation.getter(#activeLinuxEnvironment),
            returnValue: _FakeLinuxEnvironmentStrategy_4(
              this,
              Invocation.getter(#activeLinuxEnvironment),
            ),
          )
          as _i5.LinuxEnvironmentStrategy);

  @override
  set romsRootPath(String? value) => super.noSuchMethod(
    Invocation.setter(#romsRootPath, value),
    returnValueForMissingStub: null,
  );

  @override
  set emulatorsRootPath(String? value) => super.noSuchMethod(
    Invocation.setter(#emulatorsRootPath, value),
    returnValueForMissingStub: null,
  );

  @override
  set linuxSyncPreset(String? value) => super.noSuchMethod(
    Invocation.setter(#linuxSyncPreset, value),
    returnValueForMissingStub: null,
  );

  @override
  set linuxPresetRootPath(String? value) => super.noSuchMethod(
    Invocation.setter(#linuxPresetRootPath, value),
    returnValueForMissingStub: null,
  );

  @override
  set useFlatEmulatorLayout(bool? value) => super.noSuchMethod(
    Invocation.setter(#useFlatEmulatorLayout, value),
    returnValueForMissingStub: null,
  );

  @override
  set status(_i4.StorageStatus? value) => super.noSuchMethod(
    Invocation.setter(#status, value),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<String?> detectEmuDeckRoot() =>
      (super.noSuchMethod(
            Invocation.method(#detectEmuDeckRoot, []),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<_i4.StorageStatus> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i8.Future<_i4.StorageStatus>.value(
              _FakeStorageStatus_3(this, Invocation.method(#initialize, [])),
            ),
          )
          as _i8.Future<_i4.StorageStatus>);

  @override
  _i8.Future<String> getDefaultBase() =>
      (super.noSuchMethod(
            Invocation.method(#getDefaultBase, []),
            returnValue: _i8.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#getDefaultBase, []),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<String?> resolveSevenZipPath() =>
      (super.noSuchMethod(
            Invocation.method(#resolveSevenZipPath, []),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<void> resetRomsRoot() =>
      (super.noSuchMethod(
            Invocation.method(#resetRomsRoot, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> resetEmulatorsRoot() =>
      (super.noSuchMethod(
            Invocation.method(#resetEmulatorsRoot, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setLinuxSyncPreset(String? preset) =>
      (super.noSuchMethod(
            Invocation.method(#setLinuxSyncPreset, [preset]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setLinuxPresetRoot(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#setLinuxPresetRoot, [path]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void loadEmulatorPathOverrides() => super.noSuchMethod(
    Invocation.method(#loadEmulatorPathOverrides, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> setEmulatorPathOverride(String? emulatorId, String? path) =>
      (super.noSuchMethod(
            Invocation.method(#setEmulatorPathOverride, [emulatorId, path]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<String?> getEmulatorUrlOverride(String? emulatorId) =>
      (super.noSuchMethod(
            Invocation.method(#getEmulatorUrlOverride, [emulatorId]),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<void> setEmulatorUrlOverride(String? emulatorId, String? url) =>
      (super.noSuchMethod(
            Invocation.method(#setEmulatorUrlOverride, [emulatorId, url]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  String? getEmulatorPathOverride(String? emulatorId) =>
      (super.noSuchMethod(
            Invocation.method(#getEmulatorPathOverride, [emulatorId]),
          )
          as String?);

  @override
  _i8.Future<void> setEmulatorFlatpakOverride(
    String? emulatorId,
    String? packageId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setEmulatorFlatpakOverride, [
              emulatorId,
              packageId,
            ]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  String? getEmulatorFlatpakOverride(String? emulatorId) =>
      (super.noSuchMethod(
            Invocation.method(#getEmulatorFlatpakOverride, [emulatorId]),
          )
          as String?);

  @override
  _i8.Future<String?> getEffectiveFlatpakPackage(String? emulatorId) =>
      (super.noSuchMethod(
            Invocation.method(#getEffectiveFlatpakPackage, [emulatorId]),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<void> setRomsRoot(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#setRomsRoot, [path]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setEmulatorsRoot(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#setEmulatorsRoot, [path]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  bool platformSupportsArchive(String? platformSlug) =>
      (super.noSuchMethod(
            Invocation.method(#platformSupportsArchive, [platformSlug]),
            returnValue: false,
          )
          as bool);

  @override
  _i8.Future<bool> isRomDownloaded(_i3.Game? game) =>
      (super.noSuchMethod(
            Invocation.method(#isRomDownloaded, [game]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<String> getRomsDirectory() =>
      (super.noSuchMethod(
            Invocation.method(#getRomsDirectory, []),
            returnValue: _i8.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#getRomsDirectory, []),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<String> getRomDirectory(_i3.Game? game) =>
      (super.noSuchMethod(
            Invocation.method(#getRomDirectory, [game]),
            returnValue: _i8.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#getRomDirectory, [game]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<String> getRomFilePath(_i3.Game? game) =>
      (super.noSuchMethod(
            Invocation.method(#getRomFilePath, [game]),
            returnValue: _i8.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#getRomFilePath, [game]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<String?> findExistingRomPath(
    _i3.Game? game, {
    _i4.FileSystemIndex? index,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#findExistingRomPath, [game], {#index: index}),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<void> setUseFlatEmulatorLayout(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setUseFlatEmulatorLayout, [value]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<String> getEmulatorDirectory(String? emulatorId) =>
      (super.noSuchMethod(
            Invocation.method(#getEmulatorDirectory, [emulatorId]),
            returnValue: _i8.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#getEmulatorDirectory, [emulatorId]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<String> getEmulatorAppSupportDirectory(
    String? emulatorName, {
    String? platformSlug,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getEmulatorAppSupportDirectory,
              [emulatorName],
              {#platformSlug: platformSlug},
            ),
            returnValue: _i8.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(
                  #getEmulatorAppSupportDirectory,
                  [emulatorName],
                  {#platformSlug: platformSlug},
                ),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<String> getEmulatorBiosDirectory(
    String? emulatorId, {
    String? platformSlug,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getEmulatorBiosDirectory,
              [emulatorId],
              {#platformSlug: platformSlug},
            ),
            returnValue: _i8.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(
                  #getEmulatorBiosDirectory,
                  [emulatorId],
                  {#platformSlug: platformSlug},
                ),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<String> getEmulatorSystemDirectory(
    String? emulatorId, {
    String? platformSlug,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getEmulatorSystemDirectory,
              [emulatorId],
              {#platformSlug: platformSlug},
            ),
            returnValue: _i8.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(
                  #getEmulatorSystemDirectory,
                  [emulatorId],
                  {#platformSlug: platformSlug},
                ),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<void> deleteEmulator(String? emulatorId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEmulator, [emulatorId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteRom(_i3.Game? game) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRom, [game]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<String?> findEmulatorExecutable(
    String? emulatorId,
    String? executableName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#findEmulatorExecutable, [
              emulatorId,
              executableName,
            ]),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<void> launchGame(
    _i3.Game? game,
    String? romPath,
    String? emulatorId,
    String? exePath, {
    List<String>? args = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #launchGame,
              [game, romPath, emulatorId, exePath],
              {#args: args},
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i10.Process?> launchGameWithHandle(
    _i3.Game? game,
    String? romPath,
    String? emulatorId,
    String? exePath, {
    List<String>? args = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #launchGameWithHandle,
              [game, romPath, emulatorId, exePath],
              {#args: args},
            ),
            returnValue: _i8.Future<_i10.Process?>.value(),
          )
          as _i8.Future<_i10.Process?>);

  @override
  _i8.Future<void> launchStandalone(
    String? emulatorId,
    String? exePath, {
    List<String>? args = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #launchStandalone,
              [emulatorId, exePath],
              {#args: args},
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> isEmulatorInstalled(
    String? emulatorId,
    String? executableName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#isEmulatorInstalled, [
              emulatorId,
              executableName,
            ]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);
}

/// A class which mocks [RomMappingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRomMappingService extends _i1.Mock implements _i13.RomMappingService {
  MockRomMappingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  Map<String, String> getMappings() =>
      (super.noSuchMethod(
            Invocation.method(#getMappings, []),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  _i8.Future<void> updateMapping(String? path, String? romId) =>
      (super.noSuchMethod(
            Invocation.method(#updateMapping, [path, romId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  Map<String, int> getMTimes() =>
      (super.noSuchMethod(
            Invocation.method(#getMTimes, []),
            returnValue: <String, int>{},
          )
          as Map<String, int>);

  @override
  _i8.Future<void> updateMTime(String? path, int? timestamp) =>
      (super.noSuchMethod(
            Invocation.method(#updateMTime, [path, timestamp]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setLastSyncTime(int? timestamp) =>
      (super.noSuchMethod(
            Invocation.method(#setLastSyncTime, [timestamp]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  String? getRomIdForPath(String? path) =>
      (super.noSuchMethod(Invocation.method(#getRomIdForPath, [path]))
          as String?);

  @override
  _i8.Future<void> removeMapping(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#removeMapping, [path]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [LibrarySnapshotService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLibrarySnapshotService extends _i1.Mock
    implements _i14.LibrarySnapshotService {
  MockLibrarySnapshotService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<void> savePlatforms(List<_i3.Platform>? platforms) =>
      (super.noSuchMethod(
            Invocation.method(#savePlatforms, [platforms]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<_i3.Platform>> loadPlatforms() =>
      (super.noSuchMethod(
            Invocation.method(#loadPlatforms, []),
            returnValue: _i8.Future<List<_i3.Platform>>.value(<_i3.Platform>[]),
          )
          as _i8.Future<List<_i3.Platform>>);

  @override
  _i8.Future<void> saveCollections(List<Map<String, dynamic>>? collections) =>
      (super.noSuchMethod(
            Invocation.method(#saveCollections, [collections]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<Map<String, dynamic>>> loadCollections() =>
      (super.noSuchMethod(
            Invocation.method(#loadCollections, []),
            returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<void> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [MetadataCacheService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMetadataCacheService extends _i1.Mock
    implements _i15.MetadataCacheService {
  MockMetadataCacheService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.Game> get cachedGames =>
      (super.noSuchMethod(
            Invocation.getter(#cachedGames),
            returnValue: <_i3.Game>[],
          )
          as List<_i3.Game>);

  @override
  _i8.Future<void> load() =>
      (super.noSuchMethod(
            Invocation.method(#load, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> saveGames(List<_i3.Game>? games) =>
      (super.noSuchMethod(
            Invocation.method(#saveGames, [games]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updatePlatformCount(String? platformId, int? count) =>
      (super.noSuchMethod(
            Invocation.method(#updatePlatformCount, [platformId, count]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  bool isPlatformValid(String? platformId, int? remoteCount) =>
      (super.noSuchMethod(
            Invocation.method(#isPlatformValid, [platformId, remoteCount]),
            returnValue: false,
          )
          as bool);

  @override
  _i8.Future<void> invalidatePlatform(String? platformId) =>
      (super.noSuchMethod(
            Invocation.method(#invalidatePlatform, [platformId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  List<_i3.Game> getOfflineGames({
    String? platformId,
    String? search,
    List<String>? genres,
    List<String>? regions,
    List<String>? languages,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getOfflineGames, [], {
              #platformId: platformId,
              #search: search,
              #genres: genres,
              #regions: regions,
              #languages: languages,
            }),
            returnValue: <_i3.Game>[],
          )
          as List<_i3.Game>);

  @override
  _i8.Future<void> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}
