// Mocks generated by Mockito 5.4.6 from annotations
// in freegosy/test/widgets/settings_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:io' as _i9;
import 'dart:typed_data' as _i12;

import 'package:flutter/foundation.dart' as _i4;
import 'package:freegosy/core/emulator/emulator_strategy.dart' as _i14;
import 'package:freegosy/core/emulator/linux_strategies/linux_environment_strategy.dart'
    as _i3;
import 'package:freegosy/core/emulator/strategy_registry.dart' as _i13;
import 'package:freegosy/core/romm/romm_models.dart' as _i5;
import 'package:freegosy/core/romm/romm_service.dart' as _i10;
import 'package:freegosy/core/storage/app_preferences.dart' as _i11;
import 'package:freegosy/core/storage/directory_service.dart' as _i6;
import 'package:freegosy/core/storage/file_system_index.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeStorageStatus_0 extends _i1.SmartFake implements _i2.StorageStatus {
  _FakeStorageStatus_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLinuxEnvironmentStrategy_1 extends _i1.SmartFake
    implements _i3.LinuxEnvironmentStrategy {
  _FakeLinuxEnvironmentStrategy_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeValueNotifier_2<T> extends _i1.SmartFake
    implements _i4.ValueNotifier<T> {
  _FakeValueNotifier_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRomMConfig_3 extends _i1.SmartFake implements _i5.RomMConfig {
  _FakeRomMConfig_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRommCapabilities_4 extends _i1.SmartFake
    implements _i5.RommCapabilities {
  _FakeRommCapabilities_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DirectoryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDirectoryService extends _i1.Mock implements _i6.DirectoryService {
  MockDirectoryService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get romsRootPath =>
      (super.noSuchMethod(
            Invocation.getter(#romsRootPath),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#romsRootPath),
            ),
          )
          as String);

  @override
  String get emulatorsRootPath =>
      (super.noSuchMethod(
            Invocation.getter(#emulatorsRootPath),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#emulatorsRootPath),
            ),
          )
          as String);

  @override
  String get linuxSyncPreset =>
      (super.noSuchMethod(
            Invocation.getter(#linuxSyncPreset),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#linuxSyncPreset),
            ),
          )
          as String);

  @override
  bool get useFlatEmulatorLayout =>
      (super.noSuchMethod(
            Invocation.getter(#useFlatEmulatorLayout),
            returnValue: false,
          )
          as bool);

  @override
  _i2.StorageStatus get status =>
      (super.noSuchMethod(
            Invocation.getter(#status),
            returnValue: _FakeStorageStatus_0(this, Invocation.getter(#status)),
          )
          as _i2.StorageStatus);

  @override
  bool get isSteamDeck =>
      (super.noSuchMethod(Invocation.getter(#isSteamDeck), returnValue: false)
          as bool);

  @override
  _i3.LinuxEnvironmentStrategy get activeLinuxEnvironment =>
      (super.noSuchMethod(
            Invocation.getter(#activeLinuxEnvironment),
            returnValue: _FakeLinuxEnvironmentStrategy_1(
              this,
              Invocation.getter(#activeLinuxEnvironment),
            ),
          )
          as _i3.LinuxEnvironmentStrategy);

  @override
  set romsRootPath(String? value) => super.noSuchMethod(
    Invocation.setter(#romsRootPath, value),
    returnValueForMissingStub: null,
  );

  @override
  set emulatorsRootPath(String? value) => super.noSuchMethod(
    Invocation.setter(#emulatorsRootPath, value),
    returnValueForMissingStub: null,
  );

  @override
  set linuxSyncPreset(String? value) => super.noSuchMethod(
    Invocation.setter(#linuxSyncPreset, value),
    returnValueForMissingStub: null,
  );

  @override
  set linuxPresetRootPath(String? value) => super.noSuchMethod(
    Invocation.setter(#linuxPresetRootPath, value),
    returnValueForMissingStub: null,
  );

  @override
  set useFlatEmulatorLayout(bool? value) => super.noSuchMethod(
    Invocation.setter(#useFlatEmulatorLayout, value),
    returnValueForMissingStub: null,
  );

  @override
  set status(_i2.StorageStatus? value) => super.noSuchMethod(
    Invocation.setter(#status, value),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<String?> detectEmuDeckRoot() =>
      (super.noSuchMethod(
            Invocation.method(#detectEmuDeckRoot, []),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<_i2.StorageStatus> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i8.Future<_i2.StorageStatus>.value(
              _FakeStorageStatus_0(this, Invocation.method(#initialize, [])),
            ),
          )
          as _i8.Future<_i2.StorageStatus>);

  @override
  _i8.Future<String> getDefaultBase() =>
      (super.noSuchMethod(
            Invocation.method(#getDefaultBase, []),
            returnValue: _i8.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#getDefaultBase, []),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<String?> resolveSevenZipPath() =>
      (super.noSuchMethod(
            Invocation.method(#resolveSevenZipPath, []),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<void> resetRomsRoot() =>
      (super.noSuchMethod(
            Invocation.method(#resetRomsRoot, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> resetEmulatorsRoot() =>
      (super.noSuchMethod(
            Invocation.method(#resetEmulatorsRoot, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setLinuxSyncPreset(String? preset) =>
      (super.noSuchMethod(
            Invocation.method(#setLinuxSyncPreset, [preset]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setLinuxPresetRoot(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#setLinuxPresetRoot, [path]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void loadEmulatorPathOverrides() => super.noSuchMethod(
    Invocation.method(#loadEmulatorPathOverrides, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> setEmulatorPathOverride(String? emulatorId, String? path) =>
      (super.noSuchMethod(
            Invocation.method(#setEmulatorPathOverride, [emulatorId, path]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<String?> getEmulatorUrlOverride(String? emulatorId) =>
      (super.noSuchMethod(
            Invocation.method(#getEmulatorUrlOverride, [emulatorId]),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<void> setEmulatorUrlOverride(String? emulatorId, String? url) =>
      (super.noSuchMethod(
            Invocation.method(#setEmulatorUrlOverride, [emulatorId, url]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  String? getEmulatorPathOverride(String? emulatorId) =>
      (super.noSuchMethod(
            Invocation.method(#getEmulatorPathOverride, [emulatorId]),
          )
          as String?);

  @override
  _i8.Future<void> setEmulatorFlatpakOverride(
    String? emulatorId,
    String? packageId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setEmulatorFlatpakOverride, [
              emulatorId,
              packageId,
            ]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  String? getEmulatorFlatpakOverride(String? emulatorId) =>
      (super.noSuchMethod(
            Invocation.method(#getEmulatorFlatpakOverride, [emulatorId]),
          )
          as String?);

  @override
  _i8.Future<String?> getEffectiveFlatpakPackage(String? emulatorId) =>
      (super.noSuchMethod(
            Invocation.method(#getEffectiveFlatpakPackage, [emulatorId]),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<void> setRomsRoot(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#setRomsRoot, [path]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setEmulatorsRoot(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#setEmulatorsRoot, [path]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  bool platformSupportsArchive(String? platformSlug) =>
      (super.noSuchMethod(
            Invocation.method(#platformSupportsArchive, [platformSlug]),
            returnValue: false,
          )
          as bool);

  @override
  _i8.Future<bool> isRomDownloaded(_i5.Game? game) =>
      (super.noSuchMethod(
            Invocation.method(#isRomDownloaded, [game]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<String> getRomsDirectory() =>
      (super.noSuchMethod(
            Invocation.method(#getRomsDirectory, []),
            returnValue: _i8.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#getRomsDirectory, []),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<String> getRomDirectory(_i5.Game? game) =>
      (super.noSuchMethod(
            Invocation.method(#getRomDirectory, [game]),
            returnValue: _i8.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#getRomDirectory, [game]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<String> getRomFilePath(_i5.Game? game) =>
      (super.noSuchMethod(
            Invocation.method(#getRomFilePath, [game]),
            returnValue: _i8.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#getRomFilePath, [game]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<String?> findExistingRomPath(
    _i5.Game? game, {
    _i2.FileSystemIndex? index,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#findExistingRomPath, [game], {#index: index}),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<void> setUseFlatEmulatorLayout(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setUseFlatEmulatorLayout, [value]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<String> getEmulatorDirectory(String? emulatorId) =>
      (super.noSuchMethod(
            Invocation.method(#getEmulatorDirectory, [emulatorId]),
            returnValue: _i8.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#getEmulatorDirectory, [emulatorId]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<String> getEmulatorAppSupportDirectory(
    String? emulatorName, {
    String? platformSlug,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getEmulatorAppSupportDirectory,
              [emulatorName],
              {#platformSlug: platformSlug},
            ),
            returnValue: _i8.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(
                  #getEmulatorAppSupportDirectory,
                  [emulatorName],
                  {#platformSlug: platformSlug},
                ),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<String> getEmulatorBiosDirectory(
    String? emulatorId, {
    String? platformSlug,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getEmulatorBiosDirectory,
              [emulatorId],
              {#platformSlug: platformSlug},
            ),
            returnValue: _i8.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(
                  #getEmulatorBiosDirectory,
                  [emulatorId],
                  {#platformSlug: platformSlug},
                ),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<String> getEmulatorSystemDirectory(
    String? emulatorId, {
    String? platformSlug,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getEmulatorSystemDirectory,
              [emulatorId],
              {#platformSlug: platformSlug},
            ),
            returnValue: _i8.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(
                  #getEmulatorSystemDirectory,
                  [emulatorId],
                  {#platformSlug: platformSlug},
                ),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<void> deleteEmulator(String? emulatorId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEmulator, [emulatorId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteRom(_i5.Game? game) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRom, [game]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<String?> findEmulatorExecutable(
    String? emulatorId,
    String? executableName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#findEmulatorExecutable, [
              emulatorId,
              executableName,
            ]),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<void> launchGame(
    _i5.Game? game,
    String? romPath,
    String? emulatorId,
    String? exePath, {
    List<String>? args = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #launchGame,
              [game, romPath, emulatorId, exePath],
              {#args: args},
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i9.Process?> launchGameWithHandle(
    _i5.Game? game,
    String? romPath,
    String? emulatorId,
    String? exePath, {
    List<String>? args = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #launchGameWithHandle,
              [game, romPath, emulatorId, exePath],
              {#args: args},
            ),
            returnValue: _i8.Future<_i9.Process?>.value(),
          )
          as _i8.Future<_i9.Process?>);

  @override
  _i8.Future<void> launchStandalone(
    String? emulatorId,
    String? exePath, {
    List<String>? args = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #launchStandalone,
              [emulatorId, exePath],
              {#args: args},
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> isEmulatorInstalled(
    String? emulatorId,
    String? executableName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#isEmulatorInstalled, [
              emulatorId,
              executableName,
            ]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);
}

/// A class which mocks [RommService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRommService extends _i1.Mock implements _i10.RommService {
  MockRommService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.ValueNotifier<bool> get isOffline =>
      (super.noSuchMethod(
            Invocation.getter(#isOffline),
            returnValue: _FakeValueNotifier_2<bool>(
              this,
              Invocation.getter(#isOffline),
            ),
          )
          as _i4.ValueNotifier<bool>);

  @override
  _i5.RomMConfig get config =>
      (super.noSuchMethod(
            Invocation.getter(#config),
            returnValue: _FakeRomMConfig_3(this, Invocation.getter(#config)),
          )
          as _i5.RomMConfig);

  @override
  String get saveSlot =>
      (super.noSuchMethod(
            Invocation.getter(#saveSlot),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#saveSlot),
            ),
          )
          as String);

  @override
  _i5.RommCapabilities get capabilities =>
      (super.noSuchMethod(
            Invocation.getter(#capabilities),
            returnValue: _FakeRommCapabilities_4(
              this,
              Invocation.getter(#capabilities),
            ),
          )
          as _i5.RommCapabilities);

  @override
  String get authHeader =>
      (super.noSuchMethod(
            Invocation.getter(#authHeader),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#authHeader),
            ),
          )
          as String);

  @override
  void updateConfig(_i5.RomMConfig? newConfig) => super.noSuchMethod(
    Invocation.method(#updateConfig, [newConfig]),
    returnValueForMissingStub: null,
  );

  @override
  void startHeartbeat() => super.noSuchMethod(
    Invocation.method(#startHeartbeat, []),
    returnValueForMissingStub: null,
  );

  @override
  void stopHeartbeat() => super.noSuchMethod(
    Invocation.method(#stopHeartbeat, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> refreshToken(_i11.AppPreferences? prefs) =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, [prefs]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i5.RommCapabilities> fetchCapabilities() =>
      (super.noSuchMethod(
            Invocation.method(#fetchCapabilities, []),
            returnValue: _i8.Future<_i5.RommCapabilities>.value(
              _FakeRommCapabilities_4(
                this,
                Invocation.method(#fetchCapabilities, []),
              ),
            ),
          )
          as _i8.Future<_i5.RommCapabilities>);

  @override
  _i8.Future<String?> registerDevice({
    required String? name,
    required String? platform,
    String? clientVersion,
    bool? allowExisting = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registerDevice, [], {
              #name: name,
              #platform: platform,
              #clientVersion: clientVersion,
              #allowExisting: allowExisting,
            }),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<_i5.Game?> getGame(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getGame, [id]),
            returnValue: _i8.Future<_i5.Game?>.value(),
          )
          as _i8.Future<_i5.Game?>);

  @override
  _i8.Future<List<_i5.Platform>> getPlatforms() =>
      (super.noSuchMethod(
            Invocation.method(#getPlatforms, []),
            returnValue: _i8.Future<List<_i5.Platform>>.value(<_i5.Platform>[]),
          )
          as _i8.Future<List<_i5.Platform>>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getCollections() =>
      (super.noSuchMethod(
            Invocation.method(#getCollections, []),
            returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i8.Future<List<Map<String, dynamic>>>);

  @override
  String? resolveCoverUrl(_i5.Game? game) =>
      (super.noSuchMethod(Invocation.method(#resolveCoverUrl, [game]))
          as String?);

  @override
  _i8.Future<List<_i5.Game>> getGames(String? platformId) =>
      (super.noSuchMethod(
            Invocation.method(#getGames, [platformId]),
            returnValue: _i8.Future<List<_i5.Game>>.value(<_i5.Game>[]),
          )
          as _i8.Future<List<_i5.Game>>);

  @override
  _i8.Future<List<_i5.Game>> getAllGames({String? platformId}) =>
      (super.noSuchMethod(
            Invocation.method(#getAllGames, [], {#platformId: platformId}),
            returnValue: _i8.Future<List<_i5.Game>>.value(<_i5.Game>[]),
          )
          as _i8.Future<List<_i5.Game>>);

  @override
  _i8.Future<List<_i5.Game>> getRecentlyAdded({int? limit = 15}) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentlyAdded, [], {#limit: limit}),
            returnValue: _i8.Future<List<_i5.Game>>.value(<_i5.Game>[]),
          )
          as _i8.Future<List<_i5.Game>>);

  @override
  _i8.Future<List<_i5.Game>> getRecentlyPlayed({int? limit = 15}) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentlyPlayed, [], {#limit: limit}),
            returnValue: _i8.Future<List<_i5.Game>>.value(<_i5.Game>[]),
          )
          as _i8.Future<List<_i5.Game>>);

  @override
  _i8.Future<List<_i5.Game>> searchRoms({
    String? sha1,
    String? md5,
    String? search,
    String? platformId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchRoms, [], {
              #sha1: sha1,
              #md5: md5,
              #search: search,
              #platformId: platformId,
            }),
            returnValue: _i8.Future<List<_i5.Game>>.value(<_i5.Game>[]),
          )
          as _i8.Future<List<_i5.Game>>);

  @override
  _i8.Future<({List<_i5.Game> games, int total})> getGamesPage({
    int? offset = 0,
    int? limit = 50,
    String? platformId,
    String? search,
    List<String>? genres = const [],
    List<String>? regions = const [],
    List<String>? languages = const [],
    List<String>? collections = const [],
    List<String>? statuses = const [],
    bool? lastPlayed,
    bool? withCharIndex = false,
    bool? withFilterValues = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getGamesPage, [], {
              #offset: offset,
              #limit: limit,
              #platformId: platformId,
              #search: search,
              #genres: genres,
              #regions: regions,
              #languages: languages,
              #collections: collections,
              #statuses: statuses,
              #lastPlayed: lastPlayed,
              #withCharIndex: withCharIndex,
              #withFilterValues: withFilterValues,
            }),
            returnValue: _i8.Future<({List<_i5.Game> games, int total})>.value((
              games: <_i5.Game>[],
              total: 0,
            )),
          )
          as _i8.Future<({List<_i5.Game> games, int total})>);

  @override
  _i8.Future<_i5.Game?> getRandomGame() =>
      (super.noSuchMethod(
            Invocation.method(#getRandomGame, []),
            returnValue: _i8.Future<_i5.Game?>.value(),
          )
          as _i8.Future<_i5.Game?>);

  @override
  _i8.Future<List<_i5.SaveFile>> getSaves(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#getSaves, [gameId]),
            returnValue: _i8.Future<List<_i5.SaveFile>>.value(<_i5.SaveFile>[]),
          )
          as _i8.Future<List<_i5.SaveFile>>);

  @override
  String getDownloadUrl(_i5.Game? game) =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadUrl, [game]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#getDownloadUrl, [game]),
            ),
          )
          as String);

  @override
  _i8.Future<({Map<String, dynamic>? conflict, bool ok})> uploadSave(
    String? gameId,
    _i9.File? saveFile, {
    String? emulator,
    String? slot,
    String? deviceId,
    bool? autocleanup = false,
    int? autocleanupLimit = 5,
    bool? overwrite = false,
    _i9.File? screenshotFile,
    String? overrideFilename,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadSave,
              [gameId, saveFile],
              {
                #emulator: emulator,
                #slot: slot,
                #deviceId: deviceId,
                #autocleanup: autocleanup,
                #autocleanupLimit: autocleanupLimit,
                #overwrite: overwrite,
                #screenshotFile: screenshotFile,
                #overrideFilename: overrideFilename,
              },
            ),
            returnValue:
                _i8.Future<({Map<String, dynamic>? conflict, bool ok})>.value((
                  conflict: null,
                  ok: false,
                )),
          )
          as _i8.Future<({Map<String, dynamic>? conflict, bool ok})>);

  @override
  _i8.Future<bool> deleteSaves(List<int>? saveIds) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSaves, [saveIds]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<void> pruneOldSaves(String? gameId, {int? keepCount = 5}) =>
      (super.noSuchMethod(
            Invocation.method(
              #pruneOldSaves,
              [gameId],
              {#keepCount: keepCount},
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getSavesList(
    String? gameId, {
    String? deviceId,
    String? slot,
    bool? requireSuccess = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getSavesList,
              [gameId],
              {
                #deviceId: deviceId,
                #slot: slot,
                #requireSuccess: requireSuccess,
              },
            ),
            returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<Map<String, dynamic>?> getLatestSave(
    String? gameId, {
    String? deviceId,
    String? slot,
    bool? requireSuccess = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getLatestSave,
              [gameId],
              {
                #deviceId: deviceId,
                #slot: slot,
                #requireSuccess: requireSuccess,
              },
            ),
            returnValue: _i8.Future<Map<String, dynamic>?>.value(),
          )
          as _i8.Future<Map<String, dynamic>?>);

  @override
  _i8.Future<_i12.Uint8List?> downloadSave(
    String? saveUrl, {
    _i11.AppPreferences? prefs,
    String? deviceId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadSave,
              [saveUrl],
              {#prefs: prefs, #deviceId: deviceId},
            ),
            returnValue: _i8.Future<_i12.Uint8List?>.value(),
          )
          as _i8.Future<_i12.Uint8List?>);

  @override
  _i8.Future<void> recordPlaySession({
    required String? romId,
    required String? deviceId,
    required DateTime? startTime,
    required DateTime? endTime,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#recordPlaySession, [], {
              #romId: romId,
              #deviceId: deviceId,
              #startTime: startTime,
              #endTime: endTime,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<_i5.Firmware>> getFirmware({String? platformId}) =>
      (super.noSuchMethod(
            Invocation.method(#getFirmware, [], {#platformId: platformId}),
            returnValue: _i8.Future<List<_i5.Firmware>>.value(<_i5.Firmware>[]),
          )
          as _i8.Future<List<_i5.Firmware>>);

  @override
  String getFirmwareDownloadUrl(_i5.Firmware? firmware) =>
      (super.noSuchMethod(
            Invocation.method(#getFirmwareDownloadUrl, [firmware]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#getFirmwareDownloadUrl, [firmware]),
            ),
          )
          as String);

  @override
  _i8.Future<_i12.Uint8List?> downloadFirmware(
    _i5.Firmware? firmware, {
    void Function(int, int)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadFirmware,
              [firmware],
              {#onProgress: onProgress},
            ),
            returnValue: _i8.Future<_i12.Uint8List?>.value(),
          )
          as _i8.Future<_i12.Uint8List?>);

  @override
  _i8.Future<bool> updateRomProps(
    String? romId,
    _i11.AppPreferences? prefs, {
    bool? backlogged,
    bool? nowPlaying,
    int? rating,
    String? status,
    int? completion,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateRomProps,
              [romId, prefs],
              {
                #backlogged: backlogged,
                #nowPlaying: nowPlaying,
                #rating: rating,
                #status: status,
                #completion: completion,
              },
            ),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<List<_i5.RomNote>> getRomNotes(String? romId) =>
      (super.noSuchMethod(
            Invocation.method(#getRomNotes, [romId]),
            returnValue: _i8.Future<List<_i5.RomNote>>.value(<_i5.RomNote>[]),
          )
          as _i8.Future<List<_i5.RomNote>>);

  @override
  _i8.Future<bool> createRomNote(
    String? romId,
    String? title,
    String? content,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createRomNote, [romId, title, content]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> deleteRomNote(String? romId, int? noteId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRomNote, [romId, noteId]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);
}

/// A class which mocks [StrategyRegistry].
///
/// See the documentation for Mockito's code generation for more information.
class MockStrategyRegistry extends _i1.Mock implements _i13.StrategyRegistry {
  MockStrategyRegistry() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, String> get coreOverrides =>
      (super.noSuchMethod(
            Invocation.getter(#coreOverrides),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  Map<
    String,
    ({List<String> mergedSlugs, List<_i14.EmulatorStrategy> strategies})
  >
  detectConflicts() =>
      (super.noSuchMethod(
            Invocation.method(#detectConflicts, []),
            returnValue:
                <
                  String,
                  ({
                    List<String> mergedSlugs,
                    List<_i14.EmulatorStrategy> strategies,
                  })
                >{},
          )
          as Map<
            String,
            ({List<String> mergedSlugs, List<_i14.EmulatorStrategy> strategies})
          >);

  @override
  String? getPreferredEmulatorId(String? slug) =>
      (super.noSuchMethod(Invocation.method(#getPreferredEmulatorId, [slug]))
          as String?);

  @override
  _i8.Future<void> setPreference(String? canonicalSlug, String? emulatorId) =>
      (super.noSuchMethod(
            Invocation.method(#setPreference, [canonicalSlug, emulatorId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> clearPreferences() =>
      (super.noSuchMethod(
            Invocation.method(#clearPreferences, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setGameEmulatorPreference(
    String? gameId,
    String? emulatorId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setGameEmulatorPreference, [gameId, emulatorId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  String? getGameEmulatorPreference(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#getGameEmulatorPreference, [gameId]),
          )
          as String?);

  @override
  _i8.Future<void> clearGameEmulatorPreference(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#clearGameEmulatorPreference, [gameId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setGameCorePreference(String? gameId, String? coreId) =>
      (super.noSuchMethod(
            Invocation.method(#setGameCorePreference, [gameId, coreId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  String? getGameCorePreference(String? gameId) =>
      (super.noSuchMethod(Invocation.method(#getGameCorePreference, [gameId]))
          as String?);

  @override
  _i8.Future<void> clearGameCorePreference(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#clearGameCorePreference, [gameId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setCoreOverride(String? slug, String? coreId) =>
      (super.noSuchMethod(
            Invocation.method(#setCoreOverride, [slug, coreId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  String? getCoreOverride(String? slug) =>
      (super.noSuchMethod(Invocation.method(#getCoreOverride, [slug]))
          as String?);

  @override
  _i8.Future<void> clearCoreOverride(String? slug) =>
      (super.noSuchMethod(
            Invocation.method(#clearCoreOverride, [slug]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> clearAllCoreOverrides() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllCoreOverrides, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i14.EmulatorStrategy? getStrategyForSlug(
    String? platformSlug, {
    String? gameId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getStrategyForSlug,
              [platformSlug],
              {#gameId: gameId},
            ),
          )
          as _i14.EmulatorStrategy?);

  @override
  List<_i14.EmulatorStrategy> getAllStrategiesForSlug(String? platformSlug) =>
      (super.noSuchMethod(
            Invocation.method(#getAllStrategiesForSlug, [platformSlug]),
            returnValue: <_i14.EmulatorStrategy>[],
          )
          as List<_i14.EmulatorStrategy>);

  @override
  _i14.EmulatorStrategy? getStrategyById(String? id) =>
      (super.noSuchMethod(Invocation.method(#getStrategyById, [id]))
          as _i14.EmulatorStrategy?);

  @override
  void setNdsCore(String? core) => super.noSuchMethod(
    Invocation.method(#setNdsCore, [core]),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, dynamic>? getDefinition(String? emulatorId) =>
      (super.noSuchMethod(Invocation.method(#getDefinition, [emulatorId]))
          as Map<String, dynamic>?);
}
