// Mocks generated by Mockito 5.4.6 from annotations
// in freegosy/test/unit/device_id_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:io' as _i8;
import 'dart:typed_data' as _i9;

import 'package:flutter/foundation.dart' as _i2;
import 'package:freegosy/core/romm/romm_models.dart' as _i3;
import 'package:freegosy/core/romm/romm_service.dart' as _i4;
import 'package:freegosy/core/storage/app_preferences.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeValueNotifier_0<T> extends _i1.SmartFake
    implements _i2.ValueNotifier<T> {
  _FakeValueNotifier_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRomMConfig_1 extends _i1.SmartFake implements _i3.RomMConfig {
  _FakeRomMConfig_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRommCapabilities_2 extends _i1.SmartFake
    implements _i3.RommCapabilities {
  _FakeRommCapabilities_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RommService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRommService extends _i1.Mock implements _i4.RommService {
  MockRommService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ValueNotifier<bool> get isOffline =>
      (super.noSuchMethod(
            Invocation.getter(#isOffline),
            returnValue: _FakeValueNotifier_0<bool>(
              this,
              Invocation.getter(#isOffline),
            ),
          )
          as _i2.ValueNotifier<bool>);

  @override
  _i3.RomMConfig get config =>
      (super.noSuchMethod(
            Invocation.getter(#config),
            returnValue: _FakeRomMConfig_1(this, Invocation.getter(#config)),
          )
          as _i3.RomMConfig);

  @override
  String get saveSlot =>
      (super.noSuchMethod(
            Invocation.getter(#saveSlot),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#saveSlot),
            ),
          )
          as String);

  @override
  _i3.RommCapabilities get capabilities =>
      (super.noSuchMethod(
            Invocation.getter(#capabilities),
            returnValue: _FakeRommCapabilities_2(
              this,
              Invocation.getter(#capabilities),
            ),
          )
          as _i3.RommCapabilities);

  @override
  String get authHeader =>
      (super.noSuchMethod(
            Invocation.getter(#authHeader),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#authHeader),
            ),
          )
          as String);

  @override
  void updateConfig(_i3.RomMConfig? newConfig) => super.noSuchMethod(
    Invocation.method(#updateConfig, [newConfig]),
    returnValueForMissingStub: null,
  );

  @override
  void startHeartbeat() => super.noSuchMethod(
    Invocation.method(#startHeartbeat, []),
    returnValueForMissingStub: null,
  );

  @override
  void stopHeartbeat() => super.noSuchMethod(
    Invocation.method(#stopHeartbeat, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> refreshToken(_i7.AppPreferences? prefs) =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, [prefs]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i3.RommCapabilities> fetchCapabilities() =>
      (super.noSuchMethod(
            Invocation.method(#fetchCapabilities, []),
            returnValue: _i6.Future<_i3.RommCapabilities>.value(
              _FakeRommCapabilities_2(
                this,
                Invocation.method(#fetchCapabilities, []),
              ),
            ),
          )
          as _i6.Future<_i3.RommCapabilities>);

  @override
  _i6.Future<String?> registerDevice({
    required String? name,
    required String? platform,
    String? clientVersion,
    bool? allowExisting = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registerDevice, [], {
              #name: name,
              #platform: platform,
              #clientVersion: clientVersion,
              #allowExisting: allowExisting,
            }),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<_i3.Game?> getGame(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getGame, [id]),
            returnValue: _i6.Future<_i3.Game?>.value(),
          )
          as _i6.Future<_i3.Game?>);

  @override
  _i6.Future<List<_i3.Platform>> getPlatforms() =>
      (super.noSuchMethod(
            Invocation.method(#getPlatforms, []),
            returnValue: _i6.Future<List<_i3.Platform>>.value(<_i3.Platform>[]),
          )
          as _i6.Future<List<_i3.Platform>>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getCollections() =>
      (super.noSuchMethod(
            Invocation.method(#getCollections, []),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);

  @override
  String? resolveCoverUrl(_i3.Game? game) =>
      (super.noSuchMethod(Invocation.method(#resolveCoverUrl, [game]))
          as String?);

  @override
  _i6.Future<List<_i3.Game>> getGames(String? platformId) =>
      (super.noSuchMethod(
            Invocation.method(#getGames, [platformId]),
            returnValue: _i6.Future<List<_i3.Game>>.value(<_i3.Game>[]),
          )
          as _i6.Future<List<_i3.Game>>);

  @override
  _i6.Future<List<_i3.Game>> getAllGames({String? platformId}) =>
      (super.noSuchMethod(
            Invocation.method(#getAllGames, [], {#platformId: platformId}),
            returnValue: _i6.Future<List<_i3.Game>>.value(<_i3.Game>[]),
          )
          as _i6.Future<List<_i3.Game>>);

  @override
  _i6.Future<List<_i3.Game>> getRecentlyAdded({int? limit = 15}) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentlyAdded, [], {#limit: limit}),
            returnValue: _i6.Future<List<_i3.Game>>.value(<_i3.Game>[]),
          )
          as _i6.Future<List<_i3.Game>>);

  @override
  _i6.Future<List<_i3.Game>> getRecentlyPlayed({int? limit = 15}) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentlyPlayed, [], {#limit: limit}),
            returnValue: _i6.Future<List<_i3.Game>>.value(<_i3.Game>[]),
          )
          as _i6.Future<List<_i3.Game>>);

  @override
  _i6.Future<List<_i3.Game>> searchRoms({
    String? sha1,
    String? md5,
    String? search,
    String? platformId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchRoms, [], {
              #sha1: sha1,
              #md5: md5,
              #search: search,
              #platformId: platformId,
            }),
            returnValue: _i6.Future<List<_i3.Game>>.value(<_i3.Game>[]),
          )
          as _i6.Future<List<_i3.Game>>);

  @override
  _i6.Future<({List<_i3.Game> games, int total})> getGamesPage({
    int? offset = 0,
    int? limit = 50,
    String? platformId,
    String? search,
    List<String>? genres = const [],
    List<String>? regions = const [],
    List<String>? languages = const [],
    List<String>? collections = const [],
    List<String>? statuses = const [],
    bool? lastPlayed,
    bool? withCharIndex = false,
    bool? withFilterValues = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getGamesPage, [], {
              #offset: offset,
              #limit: limit,
              #platformId: platformId,
              #search: search,
              #genres: genres,
              #regions: regions,
              #languages: languages,
              #collections: collections,
              #statuses: statuses,
              #lastPlayed: lastPlayed,
              #withCharIndex: withCharIndex,
              #withFilterValues: withFilterValues,
            }),
            returnValue: _i6.Future<({List<_i3.Game> games, int total})>.value((
              games: <_i3.Game>[],
              total: 0,
            )),
          )
          as _i6.Future<({List<_i3.Game> games, int total})>);

  @override
  _i6.Future<_i3.Game?> getRandomGame() =>
      (super.noSuchMethod(
            Invocation.method(#getRandomGame, []),
            returnValue: _i6.Future<_i3.Game?>.value(),
          )
          as _i6.Future<_i3.Game?>);

  @override
  _i6.Future<List<_i3.SaveFile>> getSaves(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#getSaves, [gameId]),
            returnValue: _i6.Future<List<_i3.SaveFile>>.value(<_i3.SaveFile>[]),
          )
          as _i6.Future<List<_i3.SaveFile>>);

  @override
  String getDownloadUrl(_i3.Game? game) =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadUrl, [game]),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#getDownloadUrl, [game]),
            ),
          )
          as String);

  @override
  _i6.Future<({Map<String, dynamic>? conflict, bool ok})> uploadSave(
    String? gameId,
    _i8.File? saveFile, {
    String? emulator,
    String? slot,
    String? deviceId,
    bool? autocleanup = false,
    int? autocleanupLimit = 5,
    bool? overwrite = false,
    _i8.File? screenshotFile,
    String? overrideFilename,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadSave,
              [gameId, saveFile],
              {
                #emulator: emulator,
                #slot: slot,
                #deviceId: deviceId,
                #autocleanup: autocleanup,
                #autocleanupLimit: autocleanupLimit,
                #overwrite: overwrite,
                #screenshotFile: screenshotFile,
                #overrideFilename: overrideFilename,
              },
            ),
            returnValue:
                _i6.Future<({Map<String, dynamic>? conflict, bool ok})>.value((
                  conflict: null,
                  ok: false,
                )),
          )
          as _i6.Future<({Map<String, dynamic>? conflict, bool ok})>);

  @override
  _i6.Future<bool> deleteSaves(List<int>? saveIds) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSaves, [saveIds]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> pruneOldSaves(String? gameId, {int? keepCount = 5}) =>
      (super.noSuchMethod(
            Invocation.method(
              #pruneOldSaves,
              [gameId],
              {#keepCount: keepCount},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getSavesList(
    String? gameId, {
    String? deviceId,
    String? slot,
    bool? requireSuccess = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getSavesList,
              [gameId],
              {
                #deviceId: deviceId,
                #slot: slot,
                #requireSuccess: requireSuccess,
              },
            ),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<Map<String, dynamic>?> getLatestSave(
    String? gameId, {
    String? deviceId,
    String? slot,
    bool? requireSuccess = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getLatestSave,
              [gameId],
              {
                #deviceId: deviceId,
                #slot: slot,
                #requireSuccess: requireSuccess,
              },
            ),
            returnValue: _i6.Future<Map<String, dynamic>?>.value(),
          )
          as _i6.Future<Map<String, dynamic>?>);

  @override
  _i6.Future<_i9.Uint8List?> downloadSave(
    String? saveUrl, {
    _i7.AppPreferences? prefs,
    String? deviceId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadSave,
              [saveUrl],
              {#prefs: prefs, #deviceId: deviceId},
            ),
            returnValue: _i6.Future<_i9.Uint8List?>.value(),
          )
          as _i6.Future<_i9.Uint8List?>);

  @override
  _i6.Future<void> recordPlaySession({
    required String? romId,
    required String? deviceId,
    required DateTime? startTime,
    required DateTime? endTime,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#recordPlaySession, [], {
              #romId: romId,
              #deviceId: deviceId,
              #startTime: startTime,
              #endTime: endTime,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> sendActivityHeartbeat({
    required String? romId,
    required String? deviceId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendActivityHeartbeat, [], {
              #romId: romId,
              #deviceId: deviceId,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> clearActivityHeartbeat({required String? deviceId}) =>
      (super.noSuchMethod(
            Invocation.method(#clearActivityHeartbeat, [], {
              #deviceId: deviceId,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i3.Firmware>> getFirmware({String? platformId}) =>
      (super.noSuchMethod(
            Invocation.method(#getFirmware, [], {#platformId: platformId}),
            returnValue: _i6.Future<List<_i3.Firmware>>.value(<_i3.Firmware>[]),
          )
          as _i6.Future<List<_i3.Firmware>>);

  @override
  String getFirmwareDownloadUrl(_i3.Firmware? firmware) =>
      (super.noSuchMethod(
            Invocation.method(#getFirmwareDownloadUrl, [firmware]),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#getFirmwareDownloadUrl, [firmware]),
            ),
          )
          as String);

  @override
  _i6.Future<_i9.Uint8List?> downloadFirmware(
    _i3.Firmware? firmware, {
    void Function(int, int)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadFirmware,
              [firmware],
              {#onProgress: onProgress},
            ),
            returnValue: _i6.Future<_i9.Uint8List?>.value(),
          )
          as _i6.Future<_i9.Uint8List?>);

  @override
  _i6.Future<bool> updateRomProps(
    String? romId,
    _i7.AppPreferences? prefs, {
    bool? backlogged,
    bool? nowPlaying,
    int? rating,
    String? status,
    int? completion,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateRomProps,
              [romId, prefs],
              {
                #backlogged: backlogged,
                #nowPlaying: nowPlaying,
                #rating: rating,
                #status: status,
                #completion: completion,
              },
            ),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<List<_i3.RomNote>> getRomNotes(String? romId) =>
      (super.noSuchMethod(
            Invocation.method(#getRomNotes, [romId]),
            returnValue: _i6.Future<List<_i3.RomNote>>.value(<_i3.RomNote>[]),
          )
          as _i6.Future<List<_i3.RomNote>>);

  @override
  _i6.Future<bool> createRomNote(
    String? romId,
    String? title,
    String? content,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createRomNote, [romId, title, content]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> deleteRomNote(String? romId, int? noteId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRomNote, [romId, noteId]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);
}
